config/routes.rb
Minou::Application.routes.draw do
  resources :customers

  resources :timecodes

  resources :timedays do
  	get :statistics, on: :collection
  end

  resources :timesheets

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}

  scope "/admin" do
  	resources :users
  end
 
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :timedays
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do 
        pdf = CustomerPdf.new
        send_data pdf.render, :filename => "Cliente_#{@customer.id}.pdf",
                              :type => "application/pdf",
                              :disposition => "inline"
      end
    end
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @customer }
      else
        format.html { render action: 'new' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :address, :city, :postal_code, :codfisc, :child_name)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for(@customer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inline">
    <%= f.input :name, :label => "nome" %>
    <%= f.input :service, :label => "servizio" %>
    <%= f.input :address, :label => "indirizzo" %>
    <%= f.input :city, :label => "Città"  %>
    <%= f.input :postal_code, :label => "CAP" %>
    <%= f.input :codfisc, :label => "Cod.Fiscale" %>
    <%= f.input :child_name, :label => "Nome del Bambino" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Aggiorna Cliente</h1>

<%= render 'form' %>

<%= link_to 'Vedi', @customer %> |
<%= link_to 'Indietro', customers_path %>

app/views/customers/index.html.erb
<h1>Elenco Clienti</h1>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Servizio</th>
      <th>Indirizzo</th>
      <th>Città</th>
      <th>CAP</th>
      <th>Cod.fiscale</th>
      <th>Nome del bambino</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.service %></td>
        <td><%= customer.address %></td>
        <td><%= customer.city %></td>
        <td><%= customer.postal_code %></td>
        <td><%= customer.codfisc %></td>
        <td><%= customer.child_name %></td>
        <td><%= link_to 'Vedi', customer %></td>
        <td><%= link_to 'Aggiorna', edit_customer_path(customer) %></td>
        <td><%= link_to 'Cancella', customer, method: :delete, data: { confirm: 'sei sicuro ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuovo Cliente', new_customer_path %>

app/views/customers/new.html.erb
<h1>Nuovo Cliente</h1>

<%= render 'form' %>

<%= link_to 'Indietro', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Servizio:</strong>
  <%= @customer.service %>
</p>

<p>
  <strong>Indirizzo:</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>Località:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>CAP:</strong>
  <%= @customer.postal_code %>
</p>

<p>
  <strong>Codfisc:</strong>
  <%= @customer.codfisc %>
</p>

<p>
  <strong>Nome bambino:</strong>
  <%= @customer.child_name %>
</p>

<%= link_to 'Aggiorna', edit_customer_path(@customer) %> |
<%= link_to 'Indietro', customers_path %>
<p>
<%= link_to 'Crea PDF', customer_path(@customer, :format => "pdf") %>
</p>