config/routes.rb
Minou::Application.routes.draw do
  resources :customers

  resources :timecodes

  resources :timedays do
  	get :statistics, on: :collection
  end

  resources :timesheets

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}

  scope "/admin" do
  	resources :users
  end
 
end

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
  belongs_to :user
  has_many   :timedays, dependent: :destroy 

  def mese
  	res = case self.month 
	  	when 1 then	"Gennaio"
	  	when 2 then	"Febbraio"
	  	when 3 then	"Marzo"
	  	when 4 then	"Aprile"
	  	when 5 then	"Maggio"
	  	when 6 then	"Giugno"
	  	when 7 then	"Luglio"
	  	when 8 then	"Agosto"
	  	when 9 then	"Settembre"
	  	when 10 then "Ottobre"
	  	when 11 then "Novembre"
	  	when 12 then "Dicembre"
	  	else "Mese"
  	end
  end

  def self.totali(i_id)
  	sql = "select nome, year, month, descri, sum(ore), sum(km)
				from (
				select user_id, year, month, code1 cod, hour1 ore, km1 km, u.name nome, t.descr descri from timedays a, timesheets b, users u, timecodes t
				where a.timesheet_id = b.id and code1 is not null and b.user_id = u.id and a.code1 = t.id
				and b.id = #{i_id}
				union all
				select user_id, year, month, code2 cod, hour2 ore, km2 km, u.name nome, t.descr descri from timedays a, timesheets b, users u, timecodes t
				where a.timesheet_id = b.id and code2 is not null and b.user_id = u.id and a.code2 = t.id
				and b.id = #{i_id}
				union all
				select user_id, year, month, code3 cod, hour3 ore, km3 km, u.name nome, t.descr descri from timedays a, timesheets b, users u, timecodes t
				where a.timesheet_id = b.id and code3 is not null and b.user_id = u.id and a.code3 = t.id
				and b.id = #{i_id}
				union all
				select user_id, year, month, code4 cod, hour4 ore, km4 km, u.name nome, t.descr descri from timedays a, timesheets b, users u, timecodes t
				where a.timesheet_id = b.id and code4 is not null and b.user_id = u.id and a.code4 = t.id
				and b.id = #{i_id}
				) as foo
				group by nome, year, month, descri
				order by nome, year, month, descri"
  	connection.select_rows(sql)
  end
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  before_action :set_timesheet, only: [:show, :edit, :update, :destroy]

  # GET /timesheets
  # GET /timesheets.json
  def index
    current_year = Time.now.year
    current_month = Time.now.month
    params[:user_id] = nil if params[:user_id] == "" 
    params[:year] = nil if params[:year] == "" 

    if current_user.admin? then
      if params[:user_id] then
        @timesheets = Timesheet.where(:user_id => params[:user_id]).order(:year, :month)
      elsif params[:year] then
        @timesheets = Timesheet.where(:year => params[:year]).order(:year, :month)
      else
        @timesheets = Timesheet.all.order(:year, :month)
      end
    else
      @timesheets = Timesheet.where("user_id = ? and year <= ? and month <= ?", 
                    current_user.id, current_year, current_month).order(:year, :month)
    end
  end

  # GET /timesheets/1
  # GET /timesheets/1.json
  def show
    @timesheet = Timesheet.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do 
        pdf = TimesheetPdf.new(@timesheet)
        send_data pdf.render, :filename => "Timesheet_#{@timesheet.id}.pdf",
                              :type => "application/pdf",
                              :disposition => "inline"
      end
    end
  end

  # GET /timesheets/new
  def new
    @timesheet = Timesheet.new
  end

  # GET /timesheets/1/edit
  def edit
  end

  # POST /timesheets
  # POST /timesheets.json
  def create
    @timesheet = Timesheet.new(timesheet_params)

    respond_to do |format|
      if @timesheet.save
        format.html { redirect_to @timesheet, notice: 'Timesheet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @timesheet }
      else
        format.html { render action: 'new' }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timesheets/1
  # PATCH/PUT /timesheets/1.json
  def update
    respond_to do |format|
      if @timesheet.update(timesheet_params)
        format.html { redirect_to @timesheet, notice: 'Timesheet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timesheets/1
  # DELETE /timesheets/1.json
  def destroy
    @timesheet.destroy
    respond_to do |format|
      format.html { redirect_to timesheets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timesheet
      @timesheet = Timesheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timesheet_params
      params.require(:timesheet).permit(:year, :month, :status, :user_id)
    end
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/views/timesheets/_form.html.erb
<%= simple_form_for(@timesheet) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :year, label: "Anno" %>
    <%= f.input :month, label: "Mese" %>
    <%= f.input :status, label: "Stato", as: :boolean, boolean_style: :inline %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/timesheets/edit.html.erb
<h1>Aggiorna stato timesheet</h1>

<%= render 'form' %>

<%= link_to 'Indietro', timesheets_path %>

app/views/timesheets/index.html.erb
<% if current_user.admin? %>
  <%= form_tag timesheets_path, :method => 'get', :class => "form-search" do %>
  <%= text_field_tag :user_id, nil, :placeholder => "Utente", 
      :class => "input-medium search-query" %>
  <%= text_field_tag :year, nil, :placeholder => "anno", 
      :class => "input-medium search-query" %>
  <%= submit_tag "Cerca!", :user_id => nil, :class => "btn" %>
  <% end %>
<% else %>
  <h1>Elenco timesheets di <span><%= current_user.name %></span></h1>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>id</th>
      <th>Anno</th>
      <th>Mese</th>
      <th>Stato</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @timesheets.each do |timesheet| %>
      <tr>
        <td><%= timesheet.user.name %></td>
        <td><%= timesheet.year %></td>
        <td><%= timesheet.mese %></td>
        <td><%= timesheet.status %></td>
        <td><%= timesheet.timedays.sum(:hour1) + timesheet.timedays.sum(:hour2) + timesheet.timedays.sum(:hour3) + timesheet.timedays.sum(:hour4) %></td>
        <td><%= link_to 'Aggiorna', controller: "timedays", action: "index", foglio: timesheet.id  %></td> 
        <td><%= link_to 'Chiudi', edit_timesheet_path(timesheet) %></td>
        <td><%= link_to 'crea PDF', timesheet_path(timesheet, :format => "pdf") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/timesheets/new.html.erb
<h1>New timesheet</h1>

<%= render 'form' %>

<%= link_to 'Back', timesheets_path %>

app/views/timesheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @timesheet.year %>
</p>

<p>
  <strong>Month:</strong>
  <%= @timesheet.month %>
</p>

<p>
  <strong>Status:</strong>
  <%= @timesheet.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @timesheet.user_id %>
</p>

<%= link_to 'Edit', edit_timesheet_path(@timesheet) %> |
<%= link_to 'Back', timesheets_path %>