config/routes.rb
Minou::Application.routes.draw do
  resources :customers

  resources :timecodes

  resources :timedays do
  	get :statistics, on: :collection
  end

  resources :timesheets

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}

  scope "/admin" do
  	resources :users
  end
 
end

app/models/timecode.rb
class Timecode < ActiveRecord::Base
	has_many :timedays
	scope :prod, where(typo: 'P')
	scope :impro, where(typo: 'I')
end

app/controllers/timecodes_controller.rb
class TimecodesController < ApplicationController
  before_action :set_timecode, only: [:show, :edit, :update, :destroy]

  # GET /timecodes
  # GET /timecodes.json
  def index
    @timecodes = Timecode.all.order(:descr)
  end

  # GET /timecodes/1
  # GET /timecodes/1.json
  def show
  end

  # GET /timecodes/new
  def new
    @timecode = Timecode.new
  end

  # GET /timecodes/1/edit
  def edit
    @timecodes = Timecode.all
  end

  # POST /timecodes
  # POST /timecodes.json
  def create
    @timecode = Timecode.new(timecode_params)

    respond_to do |format|
      if @timecode.save
        format.html { redirect_to @timecode, notice: 'Timecode was successfully created.' }
        format.json { render action: 'show', status: :created, location: @timecode }
      else
        format.html { render action: 'new' }
        format.json { render json: @timecode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timecodes/1
  # PATCH/PUT /timecodes/1.json
  def update
    respond_to do |format|
      if @timecode.update(timecode_params)
        format.html { redirect_to @timecode, notice: 'Timecode was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @timecode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timecodes/1
  # DELETE /timecodes/1.json
  def destroy
    @timecode.destroy
    respond_to do |format|
      format.html { redirect_to timecodes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timecode
      @timecode = Timecode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timecode_params
      params.require(:timecode).permit(:descr, :typo)
    end
end

app/helpers/timecodes_helper.rb
module TimecodesHelper
end

app/views/timecodes/_form.html.erb
<%= simple_form_for(@timecode, :html => {:class => "form-inline" }) do |f| %>

  <%= f.error_notification %>
    <%= f.input :descr, class:"input-small" %>
    <%= f.input :typo %>

    <%= f.button :submit%>
<% end %>

app/views/timecodes/edit.html.erb
<h1>Editing timecode</h1>

<%= render 'form' %>

<%= link_to 'Show', @timecode %> |
<%= link_to 'Back', timecodes_path %>

app/views/timecodes/index.html.erb
<h1>Elenco codici</h1>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Descrizione</th>
      <th>Tipo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @timecodes.each do |timecode| %>
      <tr>
        <td><%= timecode.descr %></td>
        <td><%= timecode.typo %></td>
        <td><%= link_to 'Vedi', timecode %></td>
        <td><%= link_to 'Aggiorna', edit_timecode_path(timecode) %></td>
        <td><%= link_to 'Cancella', timecode, method: :delete, data: { confirm: 'sei sicuro ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuovo Codice', new_timecode_path %>

app/views/timecodes/new.html.erb
<h1>Nuovo codice</h1>

<%= render 'form' %>

<%= link_to 'Indietro', timecodes_path %>

app/views/timecodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descr:</strong>
  <%= @timecode.descr %>
</p>

<p>
  <strong>Typo:</strong>
  <%= @timecode.typo %>
</p>

<%= link_to 'Edit', edit_timecode_path(@timecode) %> |
<%= link_to 'Back', timecodes_path %>